# Generated by Django 5.1.6 on 2025-02-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_code',
            field=models.CharField(default='default_code', max_length=50, unique=True),
        ),
    ]
