# Generated by Django 5.1.4 on 2024-12-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_profiling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='proctoring_flag',
            field=models.BooleanField(default=False),
        ),
    ]
