# Generated by Django 5.1.4 on 2025-01-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_profiling', '0002_candidate_proctoring_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
