# Generated by Django 5.1.4 on 2025-01-29 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_profiling', '0003_alter_candidate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
