# Generated by Django 5.1.6 on 2025-02-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_profiling', '0004_candidate_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='violation_reasons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
