# Generated by Django 5.1.6 on 2025-02-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_profiling', '0005_candidate_violation_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='qadetails',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
